export const DataService = [
  {
    "id": "1",
    "logo": "bi bi-dpad",
    "title": "INSTALLATION",
    "subtitle": "We are here to build a solution to meet your needs!",
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non risus diam. Donec mattis, diam et sollicitudin imperdiet, lectus velit ultricies ante, nec sodales nisi diam eget diam. Proin lobortis felis ut auctor commodo. Proin egestas lectus felis, sit amet bibendum sapien porta eu. Suspendisse potenti. Nullam commodo interdum lorem sed cursus. Ut egestas erat dolor, vitae elementum purus imperdiet vel. Mauris volutpat eros vel dui ullamcorper hendrerit. In nec fermentum sapien. Nam ultricies varius arcu, a lobortis mauris sollicitudin ac. Aenean consectetur pulvinar elit. Suspendisse varius non sapien ac rhoncus. Nunc blandit tellus vitae dolor sagittis, non commodo velit commodo. Suspendisse sodales sem cursus velit dictum, sed maximus felis varius. Duis orci felis, venenatis eu ultrices rhoncus, vehicula a lorem. Proin faucibus elit vitae nunc tempor consectetur. In dignissim dapibus turpis, ut vestibulum orci viverra vel. Nullam eu ornare diam, facilisis lobortis elit. Nullam sit amet tellus sit amet est fringilla maximus eget et nulla. Curabitur commodo nibh vitae risus semper, quis eleifend lectus consectetur. Nulla a aliquet augue, sit amet feugiat mauris. Sed non ultrices risus, in efficitur libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent vitae mi quis purus posuere commodo. Integer tincidunt posuere egestas. Nulla tincidunt mauris ut urna vestibulum vulputate. Nulla sed ultrices purus. Maecenas dictum nec nisl ut malesuada. Vestibulum convallis sem quis efficitur iaculis. Donec id nisl ut lorem ullamcorper luctus. Quisque consectetur auctor urna. Fusce faucibus, tellus volutpat consequat viverra, elit erat fringilla lacus, sit amet imperdiet mauris augue rhoncus orci. Integer accumsan leo lectus, ut gravida augue tempus vel. Duis eu pulvinar nulla. In hac habitasse platea dictumst. Suspendisse vel lectus erat. Pellentesque ullamcorper dapibus arcu, ac mollis justo cursus nec. Nulla est dui, bibendum nec vestibulum id, molestie et eros. Maecenas faucibus, mauris a finibus bibendum, arcu lorem congue libero, at gravida nibh magna nec sapien. Nam blandit tortor sit amet diam tempus consectetur. Proin quis elementum quam. Nullam efficitur hendrerit vulputate. Donec et massa enim. Etiam faucibus ante vitae sem ultricies, venenatis feugiat mauris efficitur. Mauris gravida arcu ut diam aliquam, a congue metus congue.",
  },
  {
    "id": "2",
    "logo": "bi bi-gear",
    "title": "MAINTENANCE",
    "subtitle": "System commissioning includes full on-site user training with on going telephone support.",
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non risus diam. Donec mattis, diam et sollicitudin imperdiet, lectus velit ultricies ante, nec sodales nisi diam eget diam. Proin lobortis felis ut auctor commodo. Proin egestas lectus felis, sit amet bibendum sapien porta eu. Suspendisse potenti. Nullam commodo interdum lorem sed cursus. Ut egestas erat dolor, vitae elementum purus imperdiet vel. Mauris volutpat eros vel dui ullamcorper hendrerit. In nec fermentum sapien. Nam ultricies varius arcu, a lobortis mauris sollicitudin ac. Aenean consectetur pulvinar elit. Suspendisse varius non sapien ac rhoncus. Nunc blandit tellus vitae dolor sagittis, non commodo velit commodo. Suspendisse sodales sem cursus velit dictum, sed maximus felis varius. Duis orci felis, venenatis eu ultrices rhoncus, vehicula a lorem. Proin faucibus elit vitae nunc tempor consectetur. In dignissim dapibus turpis, ut vestibulum orci viverra vel. Nullam eu ornare diam, facilisis lobortis elit. Nullam sit amet tellus sit amet est fringilla maximus eget et nulla. Curabitur commodo nibh vitae risus semper, quis eleifend lectus consectetur. Nulla a aliquet augue, sit amet feugiat mauris. Sed non ultrices risus, in efficitur libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent vitae mi quis purus posuere commodo. Integer tincidunt posuere egestas. Nulla tincidunt mauris ut urna vestibulum vulputate. Nulla sed ultrices purus. Maecenas dictum nec nisl ut malesuada. Vestibulum convallis sem quis efficitur iaculis. Donec id nisl ut lorem ullamcorper luctus. Quisque consectetur auctor urna. Fusce faucibus, tellus volutpat consequat viverra, elit erat fringilla lacus, sit amet imperdiet mauris augue rhoncus orci.",
  },
  {
    "id": "3",
    "logo": "bi bi-tv",
    "title": "MONITORING",
    "subtitle": "For sites that are unable to have broadband we can provide connection through 3G networks.",
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non risus diam. Donec mattis, diam et sollicitudin imperdiet, lectus velit ultricies ante, nec sodales nisi diam eget diam. Proin lobortis felis ut auctor commodo. Proin egestas lectus felis, sit amet bibendum sapien porta eu. Suspendisse potenti. Nullam commodo interdum lorem sed cursus. Ut egestas erat dolor, vitae elementum purus imperdiet vel. Mauris volutpat eros vel dui ullamcorper hendrerit. In nec fermentum sapien. Nam ultricies varius arcu, a lobortis mauris sollicitudin ac. Aenean consectetur pulvinar elit. Suspendisse varius non sapien ac rhoncus. Nunc blandit tellus vitae dolor sagittis, non commodo velit commodo. Suspendisse sodales sem cursus velit dictum, sed maximus felis varius. Duis orci felis, venenatis eu ultrices rhoncus, vehicula a lorem. Proin faucibus elit vitae nunc tempor consectetur. In dignissim dapibus turpis, ut vestibulum orci viverra vel. Nullam eu ornare diam, facilisis lobortis elit. Nullam sit amet tellus sit amet est fringilla maximus eget et nulla. Curabitur commodo nibh vitae risus semper.",
  },
  {
    "id": "4",
    "logo": "bi bi-person",
    "title": "CONSULTANCY",
    "subtitle": "The company depended on external consultancy services.",
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non risus diam. Donec mattis, diam et sollicitudin imperdiet, lectus velit ultricies ante, nec sodales nisi diam eget diam. Proin lobortis felis ut auctor commodo. Proin egestas lectus felis, sit amet bibendum sapien porta eu. Suspendisse potenti. Nullam commodo interdum lorem sed cursus. Ut egestas erat dolor, vitae elementum purus imperdiet vel. Mauris volutpat eros vel dui ullamcorper hendrerit. In nec fermentum sapien. Nam ultricies varius arcu, a lobortis mauris sollicitudin ac.",
  },
]
